server:
  port: 8767

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8766/eureka/

spring:
  application:
    name: demo-gateway

zuul:
  routes:
    web:
      path: /web/**
      serviceId: demo-web

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS